### ISSUE TITLE
Laravel 7 issue installing this package

### ISSUE THREAD

**Issue by petericebear** [juanparati/Sendinblue#10]
When installing this package in a Laravel 7 application this error occurs:
Target class [swift.transport] does not exist.

https://github.com/juanparati/Sendinblue/blob/5a4986ce18e4d4b932bb8996c662e2b48e75e727/src/ServiceProvider.php#L19

I also saw this in the package with a solution to it.
https://github.com/agence-webup/laravel-sendinblue/pull/23/files

It can be updated to the same logic for this package?

**Comment by petericebear** [comment]
#11 I created a PR for L7 ServiceProvider. This might break L6 maybe a new major version needed?

**Comment by juanparati** [comment]
Hey Peter, 

Thank you for your patch. I seem that you are right and Laravel broke the library.

I merged your pull request and I tested and now it seems that it works.
I release a major version (4.x) and I removed the dependencies for the v6 of the Mail libraries. I also updated the documentation. It seems that in Laravel 7 may require some configuration changes, please take a look the README.md (I updated it).

Please feel free to came back with any feedback.
