### ISSUE TITLE
Support Composer 2.0 missing

### ISSUE THREAD

**Issue by RoodFruit** [juanparati/Sendinblue#14]
When running composer require on the package, ``` composer require juanparati/sendinblue "^8.0" ``` the following error occurs:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires juanparati/sendinblue ^8.0 -> satisfiable by juanparati/sendinblue[8.1].
    - juanparati/sendinblue 8.1 requires illuminate/mail ^8 -> found illuminate/mail[v8.0.0, ..., 8.x-dev] but it conflicts with another require.
```

This indicates Composer 2.0 is not supported yet.
See https://github.com/Dealerdirect/phpcodesniffer-composer-installer/issues/119
It's a versioning issue...

Please update, so we can happily download =D

**Comment by JuanLeadSupply** [comment]
It seems that composer 2.0 is supported.
