### ISSUE TITLE
Support Laravel v9

### ISSUE THREAD

**Issue by jeremyallebe** [juanparati/Sendinblue#16]

**Comment by juanparati** [comment]
Hi Jeremy,

I am planning to create a new branch compatible with Laravel 9 in two weeks.

Laravel 9 deprecated Swift that means that new release may be not easy to develop and may require some tests.

I am also looking if Sendinblue as a company can offer me a free account for test purposes. I will not use the test account for real marketing campaigns, just only for test that means that I will just send some transaction e-mails to a few of tests e-mails. If you know somebody in Sendinblue that can offer me a free temporal account for test the library I will be very grateful.

**Comment by jeremyallebe** [comment]
Hi Juan,

Thanks for your answer 🙂

You can create a free account on Sendinblue. It includes 300 emails to be sent by day for free ([Pricing](https://www.sendinblue.com/pricing/)).

**Comment by juanparati** [comment]
Hey Jeremy,

I created a pre-release that require some testing.

See:

https://github.com/juanparati/Sendinblue/tree/9.x

I want to collaborate with the test you can install it adding the following entries into the composer.json:

```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/juanparati/Sendinblue.git"
    }
  ],
```
```
    "require": {
      "juanparati/sendinblue": "9.x-dev",
      ...
```

**Comment by juanparati** [comment]
The first official release for Laravel 9.x was implemented.

It uses the native Symphony/Mailer transport for Sendinblue.
