### ISSUE TITLE
Composer require fails by illuminate/collections v10

### ISSUE THREAD

**Issue by kishsak** [juanparati/Sendinblue#20]
i'm using lumen framework v10. The composer require throws error as:

Problem 1
    - illuminate/mail[v9.0.0, ..., v9.52.6] require illuminate/collections ^9.0 -> found illuminate/collections[v9.0.0, ..., v9.52.6] but the package is fixed to v10.7.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - juanparati/sendinblue[9.0, ..., 9.1] require illuminate/mail ^9 -> satisfiable by illuminate/mail[v9.0.0, ..., v9.52.6].
    - Root composer.json requires juanparati/sendinblue ^9.0 -> satisfiable by juanparati/sendinblue[9.0, 9.1].

Any solutions?

**Comment by juanparati** [comment]
Please upgrade to version 10.x
