### ISSUE TITLE
sendinblue/api-v3-sdk abandoned

### ISSUE THREAD

**Issue by Cluster2a** [juanparati/Sendinblue#23]
Since the renaming of sendinblue to brevo, the new package should be used:
https://packagist.org/packages/getbrevo/brevo-php

Are there any plans for changing this?

**Comment by juanparati** [comment]
@Cluster2a : I create a new [repo](https://github.com/juanparati/BrevoSuite) that uses the new Brevo libraries.

The new report will only support Laravel 10+.
