### ISSUE TITLE
replyTo throw an error

### ISSUE THREAD

**Issue by gregory-yet** [juanparati/Sendinblue#3]
Hello,

Great package, everything works fine unless replyTo function : 

![image](https://user-images.githubusercontent.com/5993111/49833197-13deeb00-fd99-11e8-85cb-3c4622c858ec.png)

From my research, the function replyTo call setAddress (Template.php:234)
```php
        /**
	 * Set the "reply to" address of the message.
	 *
	 * @param  object|array|string  $address
	 * @param  string|null  $name
	 * @return $this
	 */
	public function replyTo($address, $name = null)
	{
		return $this->setAddress($address, $name, 'replyTo');
	}
```

But setAddress populate replyTo with multiple array (while replyTo is only one address) : 
``replyTo[] = ['name' => ..., 'address' => ...];`` 
instead of
``replyTo = ['name' => ..., 'address' => ...];``

so in TemplateTransport:116 that cause an error like undefined index because the array is multidimensional instead having address key and name key
``$mailer->setReplyTo(new SendSmtpEmailReplyTo(['email' => $message->replyTo['address'], 'name' => $message->replyTo['name']]));``

I've made an hotfix idk if it will helps or not for fixing this issue for everyone, i've replaced setAddress function in Template.php:259 : 
```php
	protected function setAddress($address, $name = null, $property = 'to')
	{
		if($property === 'replyTo') {
			$this->model->{$property} = [
				'name' => $name ?? null,
				'address' => $address,
			];

			return $this;
		}

		foreach ($this->addressesToArray($address, $name) as $recipient) {
			$recipient = $this->normalizeRecipient($recipient);

			$this->model->{$property}[] = [
				'name' => $recipient->name ?? null,
				'address' => $recipient->email,
			];
		}

		return $this;
	}
```

This catch replyTo property and instead of making multidimensional array, it makes an simple array and everything works fine after this.

Thanks, greats from France :)

**Comment by juanparati** [comment]
Thanks Gregory.

I just released a minor version to fix this issue.

**Comment by Astriel** [comment]
Greetings from France too ! 

@juanparati I think there is actually the same problem with the "from" part.

**Comment by Astriel** [comment]
`if ($property === 'replyTo' || $property === 'from') {`

Actually on the Template.php class, if I update this line (262), everything is working fine from now :)

**Comment by juanparati** [comment]
Hi @Astriel.

Thank you for reporting this bug.

I fixed it and also I released a [new version](https://github.com/juanparati/Sendinblue/releases/tag/3.1).

**Comment by Astriel** [comment]
Thanks @juanparati for your feedback. 

Looks like there is the same problem when I'm trying to plug a bcc address to a template. 

There might be a problem on TemplateTransport ? 

` 
        if ($message->bcc)
            $mailer->setBcc(new SendSmtpEmailBcc(['email' => $message->bcc['address'], 'name' => $message->bcc['name']]));
`

**Comment by juanparati** [comment]
Hey Astriel,

I was checking the code it seems that problem was totally different.

It seems that TemplateTransport was assigning CC as BCC, so it's probably that an exception was raised when CC is undefined.

I think that that I fixed the issue. Please feel free to run a "composer update".

Please feel free to come back with a feedback in case that it works. Unfortunately I cannot perform a test because I don't have access to the Sendinblue credentials until next week.
