### ISSUE TITLE
Transaction Email template attibute issue

### ISSUE THREAD

**Issue by vineetanand11** [juanparati/Sendinblue#6]
MailTemplate::attribute is not replacing the %NAME% content.
How can i replace the mail attribute? please help me.

Here is my code
MailTemplate::to('example@gmail.com');
MailTemplate::attribute('name', 'Mr User');
MailTemplate::send(3);

Thanks

**Comment by juanparati** [comment]
Have you tried to use uppercase for the attribute?
MailTemplate::attribute('NAME', 'Mr User');

**Comment by juanparati** [comment]
I tested the attribute feature and it seems that it works, however the documentation is not accurate.

Attributes are case sensitive, so if in you template you have the "%NAME%" attribute then use "NAME" using uppercases.

I updated the documentation in order provide a more accurate example.

**Comment by vineetanand11** [comment]
I used {{params.name}} in my template , Now it'is working.
